/* Generated by build_mgfx.py from ../index.html — do not edit by hand.
   Shared graphics for 무과금 오토체스 / 무과금 영토전쟁:
   MGFX.init(ctx) → post-processing (bloom + grade), rim light, VX 3D effects, realistic (HD) models. */
window.MGFX = (() => {
'use strict';
const THREE = window.THREE;
let renderer, scene, camera, host, GLOW_TEX, RING_TEX, BEAM_TEX, CHAR_SCALE = 1, MOBILE = false, CLIPS = {}, PROPS = {};
let lowFn = () => false, postFn = () => true, expMul = 1;
// names the VX module expects from the main game
const S = { get opts() { return { lowfx: lowFn() }; } }, P = {}, R = {}, buffOn = () => true;
const rnd = (a, b) => a + Math.random() * (b - a), pick = a => a[Math.floor(Math.random() * a.length)];
function propClone(name, glow) {
  const p = PROPS[name]; if (!p) return null; const c = p.clone(true);
  if (glow) c.traverse(o => { if (o.isMesh) { o.material = o.material.clone(); o.material.emissive = new THREE.Color(glow); o.material.emissiveIntensity = .9; } });
  return c;
}
const GRADE_SHADER = {
  uniforms: { tDiffuse: { value: null }, exposure: { value: 1 }, vig: { value: .32 }, sat: { value: 1.08 }, con: { value: 1.06 }, warm: { value: new THREE.Vector3(1.03, 1, .95) } },
  vertexShader: 'varying vec2 vUv; void main(){ vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }',
  fragmentShader: `uniform sampler2D tDiffuse; uniform float exposure, vig, sat, con; uniform vec3 warm; varying vec2 vUv;
    vec3 rrt(vec3 v){ vec3 a = v * (v + 0.0245786) - 0.000090537; vec3 b = v * (0.983729 * v + 0.4329510) + 0.238081; return a / b; }
    vec3 aces(vec3 c){ const mat3 i = mat3(vec3(0.59719,0.07600,0.02840), vec3(0.35458,0.90834,0.13383), vec3(0.04823,0.01566,0.83777));
      const mat3 o = mat3(vec3(1.60475,-0.10208,-0.00327), vec3(-0.53108,1.10813,-0.07276), vec3(-0.07367,-0.00605,1.07602));
      c *= exposure / 0.6; c = i * c; c = rrt(c); c = o * c; return clamp(c, 0.0, 1.0); }
    vec3 srgb(vec3 c){ return mix(c * 12.92, 1.055 * pow(c, vec3(1.0/2.4)) - 0.055, step(0.0031308, c)); }
    void main(){ vec3 c = texture2D(tDiffuse, vUv).rgb * warm; c = aces(c);
      float l = dot(c, vec3(0.2126, 0.7152, 0.0722)); c = mix(vec3(l), c, sat); c = (c - 0.5) * con + 0.5;
      vec2 d = vUv - 0.5; c *= 1.0 - vig * smoothstep(0.35, 0.95, length(d * vec2(1.25, 1.0)));
      gl_FragColor = vec4(srgb(clamp(c, 0.0, 1.0)), 1.0); }`,
};
function softTex(kind) {
  const c = document.createElement('canvas'); c.width = c.height = 128; const g = c.getContext('2d');
  if (kind === 'ring') {
    const gr = g.createRadialGradient(64, 64, 0, 64, 64, 64);
    gr.addColorStop(0, 'rgba(255,255,255,0)'); gr.addColorStop(.55, 'rgba(255,255,255,.08)'); gr.addColorStop(.78, 'rgba(255,255,255,.55)');
    gr.addColorStop(.86, 'rgba(255,255,255,1)'); gr.addColorStop(.93, 'rgba(255,255,255,.35)'); gr.addColorStop(1, 'rgba(255,255,255,0)');
    g.fillStyle = gr; g.fillRect(0, 0, 128, 128);
  } else {
    const gr = g.createLinearGradient(0, 0, 0, 128);
    gr.addColorStop(0, 'rgba(255,255,255,0)'); gr.addColorStop(.35, 'rgba(255,255,255,.55)'); gr.addColorStop(1, 'rgba(255,255,255,1)');
    g.fillStyle = gr; g.fillRect(0, 0, 128, 128);
  }
  return new THREE.CanvasTexture(c);
}
function addRim(mat) {
  if (!mat || mat.userData.rim || !mat.isMeshStandardMaterial) return;
  mat.userData.rim = true;
  mat.onBeforeCompile = sh => {
    sh.fragmentShader = sh.fragmentShader.replace('#include <output_fragment>',
      'float rimF = pow(1.0 - clamp(dot(normal, normalize(vViewPosition)), 0.0, 1.0), 2.6);\n  outgoingLight += vec3(1.0, 0.86, 0.66) * rimF * 0.45;\n#include <output_fragment>');
  };
  mat.customProgramCacheKey = () => 'rim';
}
  const V = (x, y, z) => new THREE.Vector3(x, y, z);
  const PRIMARY = { root: 'hips', hips: 'spine', spine: 'chest', chest: 'head', upperarml: 'lowerarml', lowerarml: 'wristl', wristl: 'handl', handl: 'handslotl',
    upperarmr: 'lowerarmr', lowerarmr: 'wristr', wristr: 'handr', handr: 'handslotr', upperlegl: 'lowerlegl', lowerlegl: 'footl', footl: 'toesl',
    upperlegr: 'lowerlegr', lowerlegr: 'footr', footr: 'toesr' };
  const clean = n => n.replace(/_\d+$/, '');

  // joint positions for a mesh standing on y=0, facing +z, character's left at +x, height H
  function fitJoints(pos, H) {
    const n = pos.count, P = [];
    for (let i = 0; i < n; i++) P.push([pos.getX(i), pos.getY(i), pos.getZ(i)]);
    const slice = (y0, y1, f) => P.filter(p => p[1] >= y0 * H && p[1] <= y1 * H && (!f || f(p)));
    const mean = (a, k) => a.reduce((s, p) => s + p[k], 0) / Math.max(1, a.length);
    const T = {};
    const torso = slice(.55, .75, p => Math.abs(p[0]) < .12 * H), cz = mean(torso, 2);
    T.root = V(0, 0, cz);
    T.hips = V(0, .5 * H, cz); T.spine = V(0, .6 * H, cz); T.chest = V(0, .71 * H, cz); T.head = V(0, .865 * H, cz + .005 * H);
    for (const [s, sg] of [['l', 1], ['r', -1]]) {
      const knee = slice(.26, .31, p => p[0] * sg > .01 * H), kx = mean(knee, 0), kz = mean(knee, 2);
      const ank = slice(.035, .08, p => p[0] * sg > .01 * H), ax = mean(ank, 0), az = mean(ank, 2);
      const toeP = slice(0, .05, p => p[0] * sg > .01 * H).reduce((a, p) => p[2] > a[2] ? p : a, [0, 0, -1e9]);
      T['upperleg' + s] = V(kx * .9, .48 * H, cz); T['lowerleg' + s] = V(kx, .285 * H, kz); T['foot' + s] = V(ax, .055 * H, az - .01 * H);
      T['toes' + s] = V(ax, .015 * H, Math.max(az + .04 * H, toeP[2] - .02 * H));
      // arm: shoulder joint inside the pauldron, hand tip = farthest vertex on that side
      const tip = P.reduce((a, p) => p[0] * sg > a[0] * sg ? p : a, [0, 0, 0]);
      const S = V(sg * .1 * H, .81 * H, cz), E = V(tip[0], tip[1], tip[2]), d = E.clone().sub(S);
      T['upperarm' + s] = S;
      T['lowerarm' + s] = S.clone().addScaledVector(d, .42);
      T['wrist' + s] = S.clone().addScaledVector(d, .74);
      T['hand' + s] = S.clone().addScaledVector(d, .8);
      T['handslot' + s] = S.clone().addScaledVector(d, .9);
    }
    return T;
  }

  function weights(pos, bones, segs) {
    const n = pos.count, idx = new Uint16Array(n * 4), wt = new Float32Array(n * 4), p = new THREE.Vector3(), c = new THREE.Vector3();
    const line = new THREE.Line3();
    for (let i = 0; i < n; i++) {
      p.fromBufferAttribute(pos, i);
      // pick the body part first by raw distance (so a hand next to the thigh stays on the arm),
      // then blend only inside that part (+ chest at the shoulder)
      const raw = segs.map(s => { line.set(s.a, s.b); line.closestPointToPoint(p, true, c); return c.distanceTo(p); });
      let nearest = 0; for (let k = 1; k < segs.length; k++) if (raw[k] < raw[nearest]) nearest = k;
      const fam = segs[nearest].fam;
      const best = [];
      segs.forEach((s, k) => {
        if (fam !== s.fam && !(fam !== 'body' && s.name === 'chest') && !(fam === 'body' && s.name.startsWith('upperarm'))) return;
        best.push([raw[k] / s.r, s.bi]);
      });
      best.sort((x, y) => x[0] - y[0]);
      let sum = 0; const top = best.slice(0, 4).map(([d, bi]) => { const w = 1 / Math.pow(d + .02, 4); sum += w; return [bi, w]; });
      top.forEach(([bi, w], k) => { idx[i * 4 + k] = bi; wt[i * 4 + k] = w / sum; });
    }
    return { idx, wt };
  }

  function autoRig(meshScene, kayModel, targetH) {
    // ---- mesh: merge to one geometry, stand on y=0, scale to targetH
    let src = null; meshScene.updateMatrixWorld(true);
    meshScene.traverse(o => { if (o.isMesh && !o.geometry.attributes.normal) o.geometry.computeVertexNormals(); });
    meshScene.traverse(o => { if (o.isMesh && !src) src = o; });
    const geo = src.geometry.clone(); geo.applyMatrix4(src.matrixWorld);
    geo.computeBoundingBox(); const bb = geo.boundingBox, h = bb.max.y - bb.min.y, k = targetH / h;
    geo.translate(-(bb.min.x + bb.max.x) / 2, -bb.min.y, -(bb.min.z + bb.max.z) / 2); geo.scale(k, k, k);
    const H = targetH, pos = geo.attributes.position, T = fitJoints(pos, H);

    // ---- KayKit rest pose (world)
    kayModel.updateMatrixWorld(true);
    let ksm = null; kayModel.traverse(o => { if (o.isSkinnedMesh && !ksm) ksm = o; });
    const kb = {}; for (const b of ksm.skeleton.bones) kb[clean(b.name)] = b;
    const kW = {}, kP = {}; for (const n in kb) { kW[n] = kb[n].getWorldQuaternion(new THREE.Quaternion()); kP[n] = kb[n].getWorldPosition(new THREE.Vector3()); }
    const kRootScale = kb.root.getWorldScale(new THREE.Vector3()).y;

    // ---- new skeleton with the same names / hierarchy
    const order = [], bones = {}, W = {};
    const walk = (kbone, parentName) => { const n = clean(kbone.name); if (!(n in T)) return; order.push([n, parentName]); for (const c of kbone.children) if (c.isBone) walk(c, n); };
    walk(kb.root, null);
    for (const [n, par] of order) {
      const b = new THREE.Bone(); b.name = n; bones[n] = b;
      const pc = PRIMARY[n];
      let align = par ? W[par].clone().multiply(kW[par].clone().invert()) : new THREE.Quaternion();
      if (pc && T[pc] && kP[pc]) {
        const dk = kP[pc].clone().sub(kP[n]).normalize(), dt = T[pc].clone().sub(T[n]).normalize();
        align = new THREE.Quaternion().setFromUnitVectors(dk, dt);
      }
      W[n] = align.clone().multiply(kW[n]);
      if (par) {
        bones[par].add(b);
        const inv = W[par].clone().invert();
        b.quaternion.copy(inv.clone().multiply(W[n]));
        b.position.copy(T[n].clone().sub(T[par]).applyQuaternion(inv));
      } else { b.quaternion.copy(W[n]); b.position.copy(T[n]); }
    }
    const boneList = order.map(([n]) => bones[n]);
    const skeleton = new THREE.Skeleton(boneList);

    // ---- weights from bone segments (radius tunes how far a bone reaches)
    const R = { hips: .09, spine: .09, chest: .1, head: .07, upperleg: .06, lowerleg: .05, foot: .04, toes: .03, upperarm: .045, lowerarm: .04, wrist: .03, hand: .03 };
    const segs = [];
    boneList.forEach((b, bi) => {
      const n = b.name; if (n === 'root' || n.startsWith('handslot')) return;
      const base = n.replace(/[lr]$/, ''), r = (R[base] || .05) * H;
      const a = T[n], pc = PRIMARY[n];
      let e = pc && T[pc] ? T[pc] : n === 'head' ? V(0, H, a.z) : n.startsWith('toes') ? a.clone().add(V(0, 0, .04 * H)) : a.clone().add(V(0, .05 * H, 0));
      if (n.startsWith('upperleg')) e = T[n.replace('upper', 'lower')];
      const fam = /arml$|wristl$|handl$/.test(n) ? 'arml' : /armr$|wristr$|handr$/.test(n) ? 'armr' : 'body';
      segs.push({ a: a.clone(), b: e.clone(), r, bi, fam, name: n });
    });
    const { idx, wt } = weights(pos, boneList, segs);
    geo.setAttribute('skinIndex', new THREE.Uint16BufferAttribute(idx, 4));
    geo.setAttribute('skinWeight', new THREE.Float32BufferAttribute(wt, 4));

    const mesh = new THREE.SkinnedMesh(geo, src.material);
    const root = new THREE.Group();
    root.add(bones.root); root.add(mesh);
    root.updateMatrixWorld(true);
    mesh.bind(skeleton);
    mesh.frustumCulled = false;

    // ---- clips: rotations as-is, hips height scaled, other position/scale tracks dropped
    const hipsRatio = (T.hips.y - T.root.y) / (kP.hips.y - kP.root.y);
    const retarget = clip => {
      const tracks = [];
      for (const t of clip.tracks) {
        const [bn, prop] = t.name.split('.');
        if (!bones[bn]) continue;
        if (prop === 'quaternion') tracks.push(t.clone());
        else if (prop === 'position' && bn === 'hips') { const c = t.clone(); for (let i = 0; i < c.values.length; i++) c.values[i] *= kRootScale * hipsRatio; tracks.push(c); }
      }
      return new THREE.AnimationClip(clip.name, clip.duration, tracks);
    };
    const cache = {};
    return { root, mesh, skeleton, bones, T, H, retarget, slotScale: kb.handslotr.getWorldScale(new THREE.Vector3()).x, clip: n => cache[n] || (CLIPS[n] ? (cache[n] = retarget(CLIPS[n])) : null) };
  }


const VX = (() => {
  const MAXP = 900, low = () => S && S.opts.lowfx;
  const geo = new THREE.BufferGeometry();
  const pos = new Float32Array(MAXP * 3), col = new Float32Array(MAXP * 3), siz = new Float32Array(MAXP), alp = new Float32Array(MAXP);
  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  geo.setAttribute('pcolor', new THREE.BufferAttribute(col, 3));
  geo.setAttribute('psize', new THREE.BufferAttribute(siz, 1));
  geo.setAttribute('palpha', new THREE.BufferAttribute(alp, 1));
  let pts = null, mat = null, rockMesh = null, iceMesh = null;
  const parts = [], debris = [], effects = [];
  let shakeAmt = 0, flashEl = null;
  const tmpM = new THREE.Matrix4(), tmpQ = new THREE.Quaternion(), tmpS = new THREE.Vector3(), tmpP = new THREE.Vector3(), tmpE = new THREE.Euler();
  const C = h => new THREE.Color(h);

  function init() {
    mat = new THREE.ShaderMaterial({
      uniforms: { map: { value: GLOW_TEX }, scale: { value: 400 } },
      vertexShader: 'attribute vec3 pcolor; attribute float psize; attribute float palpha; varying vec3 vC; varying float vA; uniform float scale;' +
        'void main(){ vC = pcolor; vA = palpha; vec4 mv = modelViewMatrix * vec4(position, 1.0); gl_PointSize = psize * scale / -mv.z; gl_Position = projectionMatrix * mv; }',
      fragmentShader: 'uniform sampler2D map; varying vec3 vC; varying float vA; void main(){ vec4 t = texture2D(map, gl_PointCoord); gl_FragColor = vec4(vC * t.rgb, t.a * vA); }',
      transparent: true, depthWrite: false, blending: THREE.AdditiveBlending,
    });
    pts = new THREE.Points(geo, mat); pts.frustumCulled = false; scene.add(pts);
    const mk = (g, m) => { const im = new THREE.InstancedMesh(g, m, 90); im.castShadow = true; im.frustumCulled = false; for (let i = 0; i < 90; i++) { tmpM.makeScale(0, 0, 0); im.setMatrixAt(i, tmpM); } scene.add(im); return im; };
    rockMesh = mk(new THREE.DodecahedronGeometry(.11, 0), new THREE.MeshStandardMaterial({ color: 0x5a4a3c, roughness: 1, emissive: 0x401000, emissiveIntensity: .6 }));
    iceMesh = mk(new THREE.OctahedronGeometry(.1, 0), new THREE.MeshStandardMaterial({ color: 0xbfe8ff, roughness: .2, metalness: .1, emissive: 0x3a8ad0, emissiveIntensity: .7, transparent: true, opacity: .9 }));
    rockMesh.userData.free = [...Array(90).keys()]; iceMesh.userData.free = [...Array(90).keys()];
    flashEl = document.createElement('div');
    flashEl.style.cssText = 'position:absolute;inset:0;pointer-events:none;opacity:0;z-index:2;mix-blend-mode:screen';
    host.appendChild(flashEl);
  }

  // ---------- particles ----------
  function emit(o) {
    if (parts.length >= MAXP) return;
    const c = o.color instanceof THREE.Color ? o.color : C(o.color || 0xffffff);
    parts.push({ x: o.x, y: o.y, z: o.z, vx: o.vx || 0, vy: o.vy || 0, vz: o.vz || 0, t: 0, life: o.life || .6, size: o.size || .3, grow: o.grow || 0,
      r: c.r, g: c.g, b: c.b, grav: o.grav || 0, drag: o.drag || 0, a: o.a != null ? o.a : 1 });
  }
  function burst(x, z, y, n, o = {}) {
    n = Math.round(n * (low() ? .5 : 1));
    for (let i = 0; i < n; i++) {
      const a = Math.random() * 6.283, el2 = (o.cone != null ? o.cone : 1) * (Math.random() * 1.2 - .2), sp = (o.speed || 3) * (.4 + Math.random() * .8);
      emit({ x: x + (Math.random() - .5) * (o.spread || .2), y: y + (Math.random() - .5) * (o.spread || .2), z: z + (Math.random() - .5) * (o.spread || .2),
        vx: Math.cos(a) * Math.cos(el2) * sp, vy: Math.sin(el2) * sp + (o.up || 0), vz: Math.sin(a) * Math.cos(el2) * sp,
        life: (o.life || .6) * (.6 + Math.random() * .7), size: (o.size || .3) * (.6 + Math.random() * .8), color: Array.isArray(o.color) ? o.color[i % o.color.length] : o.color,
        grav: o.grav != null ? o.grav : -4, drag: o.drag != null ? o.drag : 1.5, grow: o.grow || 0 });
    }
  }
  // ---------- debris ----------
  function chunks(kind, x, z, n, o = {}) {
    const im = kind === 'ice' ? iceMesh : rockMesh; n = Math.round(n * (low() ? .5 : 1));
    for (let i = 0; i < n && im.userData.free.length; i++) {
      const a = Math.random() * 6.283, sp = (o.speed || 3.5) * (.5 + Math.random() * .7);
      debris.push({ im, idx: im.userData.free.pop(), x: x + Math.cos(a) * (o.r || .3), y: o.y || .2, z: z + Math.sin(a) * (o.r || .3), vx: Math.cos(a) * sp, vy: 3 + Math.random() * (o.up || 4), vz: Math.sin(a) * sp,
        rx: Math.random() * 6, ry: Math.random() * 6, wr: (Math.random() - .5) * 14, t: 0, life: 1 + Math.random() * .6, s: (o.size || 1) * (.6 + Math.random() * .9) });
    }
  }
  // ---------- shared materials / geometry ----------
  const addMat = (c, o = 1) => new THREE.MeshBasicMaterial({ color: C(c), transparent: true, opacity: o, blending: THREE.AdditiveBlending, depthWrite: false, side: THREE.DoubleSide });
  const SPHERE = new THREE.SphereGeometry(1, 20, 14), PLANE = new THREE.PlaneGeometry(2, 2), CONE = new THREE.ConeGeometry(.16, 1, 6), BEAM = new THREE.CylinderGeometry(.5, .5, 1, 18, 1, true);
  function add(obj, upd) { scene.add(obj); effects.push({ obj, upd, t: 0 }); return obj; }
  const ringTex = () => RING_TEX;

  // ---------- building blocks ----------
  function shockwave(x, z, r, color, dur = .5, y = .07) {
    const m = addMat(color); m.map = ringTex();
    const o = new THREE.Mesh(PLANE, m); o.rotation.x = -Math.PI / 2; o.position.set(x, y, z);
    add(o, (e, dt) => { const p = e.t / dur, s = r * (.15 + p * .95); o.scale.set(s, s, s); m.opacity = 1 - p; return p < 1; });
  }
  function fireball(x, y, z, r, color, dur = .45) {
    const core = new THREE.Mesh(SPHERE, addMat(0xfff2c0)), shell = new THREE.Mesh(SPHERE, addMat(color, .8));
    core.position.set(x, y, z); shell.position.set(x, y, z);
    add(core, e => { const p = e.t / (dur * .6), s = r * .45 * (.4 + p); core.scale.set(s, s, s); core.material.opacity = 1 - p; return p < 1; });
    add(shell, e => { const p = e.t / dur, s = r * (.3 + p * .8); shell.scale.set(s, s * .8, s); shell.material.opacity = .85 * (1 - p) * (1 - p); return p < 1; });
  }
  function scorch(x, z, r, dur = 5) {
    const m = new THREE.MeshBasicMaterial({ map: GLOW_TEX, color: 0x000000, transparent: true, opacity: .55, depthWrite: false });
    const o = new THREE.Mesh(PLANE, m); o.rotation.x = -Math.PI / 2; o.position.set(x, .03, z); o.scale.setScalar(r);
    add(o, e => { m.opacity = .55 * Math.min(1, (dur - e.t) / 1.5); return e.t < dur; });
  }
  function shake(v) { shakeAmt = Math.max(shakeAmt, v); }
  function flash(color = 'rgba(255,240,200,.55)', dur = .25) {
    if (!flashEl) return; flashEl.style.transition = 'none'; flashEl.style.background = `radial-gradient(circle at 50% 50%, ${color}, transparent 70%)`; flashEl.style.opacity = '1';
    requestAnimationFrame(() => { flashEl.style.transition = `opacity ${dur}s ease-out`; flashEl.style.opacity = '0'; });
  }
  // jagged bolt between two points, flickers for a moment
  function lightning(a, b, color = 0x9fd8ff, dur = .28, width = .045) {
    const make = () => {
      const pts2 = [], n = 9, d = b.clone().sub(a), side = new THREE.Vector3(-d.z, 0, d.x).normalize();
      for (let i = 0; i <= n; i++) {
        const t = i / n, p = a.clone().addScaledVector(d, t), j = (i === 0 || i === n) ? 0 : (Math.random() - .5) * .55 * Math.sin(t * Math.PI) * Math.min(1.5, d.length() * .25 + .4);
        p.addScaledVector(side, j); p.y += (Math.random() - .5) * .3 * Math.sin(t * Math.PI); pts2.push(p);
      }
      return new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts2), 24, width, 4, false);
    };
    const m = addMat(color), core = addMat(0xffffff);
    const o = new THREE.Mesh(make(), m); o.userData.own = true;
    const c = new THREE.Mesh(o.geometry, core); c.scale.setScalar(1); o.add(c);
    let next = .06;
    add(o, (e) => {
      if (e.t > next) { next += .06; o.geometry.dispose(); o.geometry = make(); c.geometry = o.geometry; }
      const p = e.t / dur; m.opacity = 1 - p; core.opacity = (1 - p) * .9; return p < 1;
    });
    burst(b.x, b.z, b.y, 14, { color: [0xcfeaff, 0x7fc0ff], speed: 3, life: .35, size: .22, grav: -2 });
  }
  // ice spikes bursting out of the ground in a ring, then shattering
  function spikes(x, z, r, n = 10) {
    n = Math.round(n * (low() ? .6 : 1));
    for (let i = 0; i < n; i++) {
      const a = i / n * 6.283 + Math.random() * .4, rr = r * (.35 + Math.random() * .65), h = .7 + Math.random() * .8;
      const m = new THREE.MeshStandardMaterial({ color: 0xcfeeff, emissive: 0x5aa8ff, emissiveIntensity: .9, roughness: .15, transparent: true, opacity: .92 });
      const o = new THREE.Mesh(CONE, m); o.position.set(x + Math.cos(a) * rr, 0, z + Math.sin(a) * rr);
      o.rotation.set((Math.random() - .5) * .5, 0, (Math.random() - .5) * .5); o.castShadow = true;
      const delay = Math.random() * .12;
      add(o, e => {
        const t = e.t - delay; if (t < 0) { o.scale.set(1, .001, 1); return true; }
        const up = Math.min(1, t / .12); o.scale.set(1, h * up, 1); o.position.y = h * up * .5;
        if (t > .55 && !o.userData.broke) { o.userData.broke = true; chunks('ice', o.position.x, o.position.z, 3, { speed: 2, up: 2, y: h * .5, size: .9 }); }
        if (t > .55) m.opacity = Math.max(0, .92 - (t - .55) * 5);
        return t < .75;
      });
    }
  }
  // translucent shield shell following an entity
  function dome(ent, dur, color = 0x8fb8ff) {
    const m = new THREE.ShaderMaterial({
      uniforms: { c: { value: C(color) }, t: { value: 0 }, a: { value: 1 } },
      vertexShader: 'varying vec3 vN; varying vec3 vV; void main(){ vec4 mv = modelViewMatrix * vec4(position,1.0); vN = normalize(normalMatrix * normal); vV = normalize(-mv.xyz); gl_Position = projectionMatrix * mv; }',
      fragmentShader: 'uniform vec3 c; uniform float t; uniform float a; varying vec3 vN; varying vec3 vV; void main(){ float f = pow(1.0 - abs(dot(vN, vV)), 2.2); float band = 0.5 + 0.5 * sin(t * 4.0 + vN.y * 10.0); gl_FragColor = vec4(c * (0.12 + f * 0.9 + band * 0.08), (0.04 + f * 0.55) * a); }',
      transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide,
    });
    const o = new THREE.Mesh(SPHERE, m), h = ent.act ? ent.act.h : 1.5;
    add(o, (e) => {
      const grow = Math.min(1, e.t / .2), fade = Math.min(1, (dur - e.t) / .4), s = h * .62 * grow;
      o.scale.set(s * 1.05, s * 1.12, s * 1.05); o.position.set(ent.x, h * .5, ent.y); m.uniforms.t.value = e.t; m.uniforms.a.value = fade;
      return e.t < dur && !(ent === P && R.dead);
    });
    shockwave(ent.x, ent.y, 2.2, color, .45);
  }
  // column of light dropping from the sky
  function pillar(x, z, color = 0xffe08a, h = 9) {
    const m = addMat(color); m.map = BEAM_TEX;
    const o = new THREE.Mesh(BEAM, m); o.position.set(x, h / 2, z);
    add(o, e => { const p = e.t / .55, w = p < .15 ? .2 + p * 3 : .65 * (1 - (p - .15) / .85); o.scale.set(Math.max(.04, w), h, Math.max(.04, w)); m.opacity = .7 * (1 - p * p); return p < 1; });
    shockwave(x, z, 1.8, color, .45);
    burst(x, z, .2, 18, { color: [0xfff4c0, color], speed: 2.5, up: 2.5, life: .7, size: .26, grav: -1 });
  }
  // falling meteor with a flame trail, calls onHit on impact
  function meteor(x, z, dur, onHit) {
    const rock = new THREE.Mesh(new THREE.DodecahedronGeometry(.45, 0), new THREE.MeshStandardMaterial({ color: 0x3a2a20, emissive: 0xff5a10, emissiveIntensity: 1.4, roughness: .9 }));
    rock.userData.own = true; rock.castShadow = true;
    const glow = new THREE.Sprite(new THREE.SpriteMaterial({ map: GLOW_TEX, color: 0xff8a30, blending: THREE.AdditiveBlending, depthWrite: false })); glow.scale.setScalar(2.6); rock.add(glow);
    const sx = x - 4, sy = 11, sz = z - 3;
    add(rock, e => {
      const p = Math.min(1, e.t / dur), q = p * p;
      rock.position.set(sx + (x - sx) * q, sy + (0 - sy) * q, sz + (z - sz) * q); rock.rotation.x += .2; rock.rotation.y += .13;
      for (let k = 0; k < (low() ? 2 : 4); k++) emit({ x: rock.position.x + (Math.random() - .5) * .4, y: rock.position.y + (Math.random() - .5) * .4, z: rock.position.z + (Math.random() - .5) * .4,
        vx: (Math.random() - .5), vy: Math.random(), vz: (Math.random() - .5), life: .5, size: .5 + Math.random() * .4, color: k % 2 ? 0xff6a20 : 0xffc060, grav: 1, drag: 2 });
      if (p >= 1) { onHit(); return false; }
      return true;
    });
    // landing marker
    const m = addMat(0xff4010, .5); m.map = ringTex();
    const mk = new THREE.Mesh(PLANE, m); mk.rotation.x = -Math.PI / 2; mk.position.set(x, .06, z);
    add(mk, e => { const p = e.t / dur, s = 3.2 * (1 - p * .3); mk.scale.set(s, s, s); m.opacity = .3 + .4 * Math.abs(Math.sin(e.t * 18)); return p < 1; });
  }
  function bigBoom(x, z, r, color = 0xff6a20) {
    fireball(x, .6, z, r, color, .6); shockwave(x, z, r * 1.25, color, .55); shockwave(x, z, r * .8, 0xffe0a0, .35);
    burst(x, z, .5, 50, { color: [0xffd070, 0xff7a2a, 0xff4010], speed: 6, up: 2, life: .9, size: .4, grav: -6, drag: 1.2 });
    burst(x, z, .8, 16, { color: 0x3a3028, speed: 1.2, up: 1.6, life: 1.4, size: .9, grav: .6, drag: .8 }); // dark smoke puffs (dim additive)
    chunks('rock', x, z, 12, { speed: 4, up: 5, size: 1.2 }); scorch(x, z, r * .9); shake(.5); flash('rgba(255,170,90,.45)');
  }
  function smallBoom(x, z, r, color = 0xff8a3a) {
    fireball(x, .7, z, r * .8, color, .4); shockwave(x, z, r, color, .4);
    burst(x, z, .7, 22, { color: [0xffd070, color], speed: 4, up: 1.5, life: .55, size: .3, grav: -5 }); scorch(x, z, r * .6, 3); shake(.12);
  }

  // ---------- melee: a bright sword arc that sweeps and fades ----------
  function slash(x, z, y = .9, r = 1.2, color = 0xdfeaff, dur = .3, tilt = rnd(-.5, .5)) {
    const g = new THREE.RingGeometry(.72, 1, 36, 1, 0, Math.PI * .95), m = addMat(color);
    const o = new THREE.Mesh(g, m); o.userData.own = true; o.position.set(x, y, z);
    o.rotation.set(-Math.PI / 2 + tilt, 0, rnd(0, 6.28)); o.scale.setScalar(r);
    const core = new THREE.Mesh(new THREE.RingGeometry(.9, .97, 36, 1, 0, Math.PI * .95), addMat(0xffffff)); core.userData.own = true; o.add(core);
    add(o, e => { const p = e.t / dur; o.rotation.z += .09; const s = r * (.8 + p * .35); o.scale.set(s, s, s); m.opacity = 1 - p; core.material.opacity = 1 - p; return p < 1; });
    burst(x, z, y, 10, { color: [0xffffff, color], speed: 3.5, life: .3, size: .18, grav: -3 });
  }
  // ---------- whirlwind: blades spinning around an entity ----------
  function whirl(ent, r = 2.4, color = 0xe8f0ff, dur = .5) {
    for (const [h, dir, th] of [[.75, 1, 1.6], [1.05, -1, 1.2]]) {
      const m = addMat(color), o = new THREE.Mesh(new THREE.RingGeometry(.8, 1, 48, 1, 0, Math.PI * th), m); o.userData.own = true;
      o.rotation.x = -Math.PI / 2;
      add(o, e => { const p = e.t / dur, s = r * (.55 + p * .5); o.position.set(ent.x, h, ent.y); o.scale.set(s, s, s); o.rotation.z += dir * .45; m.opacity = (1 - p) * .9; return p < 1; });
    }
    for (let k = 0; k < (low() ? 14 : 28); k++) { const a = rnd(0, 6.28); emit({ x: ent.x + Math.cos(a) * r * .6, y: rnd(.1, 1), z: ent.y + Math.sin(a) * r * .6, vx: -Math.sin(a) * 5 + Math.cos(a) * 2, vy: rnd(0, 1), vz: Math.cos(a) * 5 + Math.sin(a) * 2, life: .45, size: rnd(.15, .3), color: k % 3 ? color : 0xb0a080, grav: -1, drag: 2.5 }); }
    shockwave(ent.x, ent.y, r, color, .45);
  }
  // ---------- ground cracks glowing outward from a point ----------
  function cracks(x, z, r, color = 0xffa040, dur = 1.4) {
    const n = low() ? 6 : 9;
    for (let i = 0; i < n; i++) {
      const a = i / n * 6.283 + rnd(-.2, .2), len = r * rnd(.6, 1), m = addMat(color);
      const o = new THREE.Mesh(new THREE.PlaneGeometry(.09, 1), m); o.userData.own = true;
      o.rotation.set(-Math.PI / 2, 0, -a + Math.PI / 2); o.position.set(x, .045, z);
      add(o, e => { const grow = Math.min(1, e.t / .15), L = len * grow; o.scale.set(1 + (1 - grow), L, 1); o.position.set(x + Math.cos(a) * L / 2, .045, z + Math.sin(a) * L / 2); m.opacity = Math.max(0, 1 - e.t / dur); return e.t < dur; });
    }
  }
  // ---------- arrows raining from the sky onto an area ----------
  function arrowRain(x, z, r, n, dur = .5, color = 0xbfe8a0, onLand) {
    n = Math.round(n * (low() ? .6 : 1));
    for (let i = 0; i < n; i++) {
      const a = rnd(0, 6.28), d = Math.sqrt(Math.random()) * r, tx = x + Math.cos(a) * d, tz = z + Math.sin(a) * d, delay = rnd(0, dur), sx = tx - 1.2, sz = tz - .8, sy = 7;
      const o = propClone('arrow_bow'); if (!o) continue;
      o.scale.setScalar(CHAR_SCALE * 1.3); o.visible = false;
      const dir = new THREE.Vector3(tx - sx, -sy, tz - sz).normalize(); o.quaternion.setFromUnitVectors(new THREE.Vector3(0, 0, 1), dir);
      let landed = false;
      add(o, e => {
        const t = e.t - delay; if (t < 0) return true; o.visible = true;
        const p = Math.min(1, t / .28);
        o.position.set(sx + (tx - sx) * p, sy * (1 - p) + .15, sz + (tz - sz) * p);
        if (p < 1) emit({ x: o.position.x, y: o.position.y + .3, z: o.position.z, life: .18, size: .16, color, grav: 0 });
        else if (!landed) { landed = true; burst(tx, tz, .1, 4, { color: [0xd8c8a0, color], speed: 1.4, up: .8, life: .3, size: .16, grav: -4 }); if (onLand) onLand(tx, tz); }
        return t < .28 + .35;
      });
    }
  }
  // ---------- a straight bright beam (piercing shot) ----------
  function beam(a, b, color = 0xffe08a, dur = .3, w = .07) {
    const d = b.clone().sub(a), L = d.length(), m = addMat(color);
    const o = new THREE.Mesh(new THREE.CylinderGeometry(w, w, 1, 8, 1, true), m); o.userData.own = true;
    o.position.copy(a).addScaledVector(d, .5); o.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), d.clone().normalize()); o.scale.set(1, L, 1);
    add(o, e => { const p = e.t / dur; o.scale.set(1 + p * 2, L, 1 + p * 2); m.opacity = 1 - p; return p < 1; });
  }
  // ---------- toxic cloud lingering at a spot ----------
  function toxic(ent, dur = 6) {
    const holder = new THREE.Object3D();
    add(holder, e => {
      if (ent.dead) return false;
      if (Math.random() < (low() ? .35 : .7)) emit({ x: ent.x + rnd(-.4, .4), y: rnd(.2, 1.2), z: ent.y + rnd(-.4, .4), vy: rnd(.3, .9), life: rnd(.6, 1), size: rnd(.3, .55), color: Math.random() < .5 ? 0x50e060 : 0x2a9a3a, grav: .2, drag: 1, a: .7 });
      return e.t < dur;
    });
  }
  // ---------- buff aura that follows an entity while the buff lasts ----------
  function aura(ent, dur, kind) {
    const cfg = {
      rage: { c: [0xff4020, 0xffa060], rate: .8, up: [1.2, 2.4], r: .5, size: .26 },
      avatar: { c: [0xff7a20, 0xffd070, 0xff4010], rate: 1.4, up: [1.6, 3], r: .55, size: .32 },
      wind: { c: [0x8ff0d8, 0xd8fff4], rate: .9, up: [.2, .6], r: .7, size: .2, orbit: 1 },
      eagle: { c: [0xffe08a, 0xfff6c8], rate: .6, up: [.1, .4], r: .35, size: .2, head: 1 },
    }[kind]; if (!cfg) return;
    const holder = new THREE.Object3D();
    add(holder, e => {
      const h = ent.act ? ent.act.h : 1.5;
      if (Math.random() < cfg.rate * (low() ? .5 : 1)) {
        const a = rnd(0, 6.28), rr = cfg.r * rnd(.6, 1.1);
        emit({ x: ent.x + Math.cos(a) * rr, y: cfg.head ? h + .25 : rnd(.05, h * .6), z: ent.y + Math.sin(a) * rr,
          vx: cfg.orbit ? -Math.sin(a) * 2 : 0, vy: rnd(cfg.up[0], cfg.up[1]), vz: cfg.orbit ? Math.cos(a) * 2 : 0, life: rnd(.5, .8), size: cfg.size * rnd(.7, 1.2), color: pick(cfg.c), grav: 0, drag: 1.5 });
      }
      return e.t < dur && !(ent === P && (R.dead || !buffOn(kind)));
    });
  }

  function update(dt) {
    if (!pts) return;
    // particles
    let n = 0;
    for (let i = parts.length - 1; i >= 0; i--) {
      const p = parts[i]; p.t += dt;
      if (p.t >= p.life) { parts[i] = parts[parts.length - 1]; parts.pop(); continue; }
      const k = Math.max(0, 1 - p.drag * dt); p.vx *= k; p.vy = p.vy * k + p.grav * dt; p.vz *= k;
      p.x += p.vx * dt; p.y = Math.max(.02, p.y + p.vy * dt); p.z += p.vz * dt;
    }
    for (const p of parts) {
      const f = p.t / p.life;
      pos[n * 3] = p.x; pos[n * 3 + 1] = p.y; pos[n * 3 + 2] = p.z; col[n * 3] = p.r; col[n * 3 + 1] = p.g; col[n * 3 + 2] = p.b;
      siz[n] = p.size * (1 + p.grow * f); alp[n] = p.a * (f < .15 ? f / .15 : 1 - (f - .15) / .85); n++;
    }
    geo.setDrawRange(0, n);
    for (const k of ['position', 'pcolor', 'psize', 'palpha']) geo.attributes[k].needsUpdate = true;
    const bs = renderer.getDrawingBufferSize(tmpP); mat.uniforms.scale.value = bs.y / (2 * Math.tan(camera.fov * Math.PI / 360));
    // debris
    for (let i = debris.length - 1; i >= 0; i--) {
      const d = debris[i]; d.t += dt; d.vy -= 12 * dt; d.x += d.vx * dt; d.y += d.vy * dt; d.z += d.vz * dt;
      if (d.y < .05) { d.y = .05; d.vy *= -.3; d.vx *= .6; d.vz *= .6; }
      d.rx += d.wr * dt; d.ry += d.wr * .7 * dt;
      const s = d.s * Math.min(1, (d.life - d.t) * 3);
      tmpM.compose(tmpP.set(d.x, d.y, d.z), tmpQ.setFromEuler(tmpE.set(d.rx, d.ry, 0)), tmpS.set(s, s, s));
      if (d.t >= d.life) { tmpM.makeScale(0, 0, 0); d.im.userData.free.push(d.idx); debris.splice(i, 1); }
      d.im.setMatrixAt(d.idx, tmpM); d.im.instanceMatrix.needsUpdate = true;
    }
    // mesh effects
    for (let i = effects.length - 1; i >= 0; i--) {
      const e = effects[i]; e.t += dt;
      if (!e.upd(e, dt)) { scene.remove(e.obj); if (e.obj.userData.own) e.obj.geometry.dispose(); e.obj.traverse(n => { if (n.material && n.material.dispose) n.material.dispose(); }); effects.splice(i, 1); }
    }
    shakeAmt = Math.max(0, shakeAmt - dt * 1.6);
  }
  function camShake(cam) { if (shakeAmt > 0) { const s = shakeAmt * .35; cam.position.x += (Math.random() - .5) * s; cam.position.y += (Math.random() - .5) * s; cam.position.z += (Math.random() - .5) * s; } }
  function clear() {
    parts.length = 0;
    for (const d of debris) { tmpM.makeScale(0, 0, 0); d.im.setMatrixAt(d.idx, tmpM); d.im.userData.free.push(d.idx); d.im.instanceMatrix.needsUpdate = true; } debris.length = 0;
    for (const e of effects) { scene.remove(e.obj); if (e.obj.userData.own) e.obj.geometry.dispose(); } effects.length = 0;
  }
  return { init, update, clear, camShake, emit, burst, chunks, shockwave, fireball, scorch, shake, flash, lightning, spikes, dome, pillar, meteor, bigBoom, smallBoom, slash, whirl, cracks, arrowRain, beam, toxic, aura };
})();

/* ---------- post-processing ---------- */
let post = null;
function setupPost() {
  if (!THREE.EffectComposer || !THREE.UnrealBloomPass) return;
  const gl2 = renderer.capabilities.isWebGL2, hf = gl2 && renderer.extensions.has('EXT_color_buffer_float');
  const rt = new THREE.WebGLRenderTarget(4, 4, { type: hf ? THREE.HalfFloatType : THREE.UnsignedByteType, samples: gl2 ? (MOBILE ? 2 : 4) : 0 });
  const composer = new THREE.EffectComposer(renderer, rt);
  composer.addPass(new THREE.RenderPass(scene, camera));
  const bloom = new THREE.UnrealBloomPass(new THREE.Vector2(256, 256), .55, .45, .82);
  composer.addPass(bloom);
  const grade = new THREE.ShaderPass(GRADE_SHADER);
  composer.addPass(grade);
  post = { composer, bloom, grade };
}
const camBase = new THREE.Vector3();
function render() {
  // camera shake is applied for this frame only (these games place the camera once on resize)
  camBase.copy(camera.position); VX.camShake(camera);
  if (post && postFn() && !lowFn()) { post.grade.uniforms.exposure.value = renderer.toneMappingExposure * expMul; post.composer.render(); }
  else renderer.render(scene, camera);
  camera.position.copy(camBase);
}
function resize(W, H, dpr) {
  if (post) { post.composer.setPixelRatio(dpr); post.composer.setSize(W, H); post.bloom.resolution.set(W / 2, H / 2); }
}

/* ---------- realistic models ----------
   base: folder with <name>.txt (base64 GLB) and list.json. Class bodies (knight/elf/mage) are always there;
   monster/polymorph bodies are listed in list.json. A body is loaded the first time it is asked for. */
const HD = {}, PENDING = {}, AVAIL = { knight: 1.12, elf: 1.06, mage: 1.1 };
let hdBase = '', kayKnight = null, charH = 1, onReady = () => {};
function parseB64(b64) {
  return new Promise((ok, bad) => {
    const bin = atob(b64.trim()), u8 = new Uint8Array(bin.length);
    for (let k = 0; k < bin.length; k++) u8[k] = bin.charCodeAt(k);
    const cib = window.createImageBitmap; window.createImageBitmap = undefined;
    try { new THREE.GLTFLoader().parse(u8.buffer, '', ok, bad); } finally { window.createImageBitmap = cib; }
  });
}
async function hdSetup(o) {
  hdBase = o.base; kayKnight = o.knight; charH = o.charH; onReady = o.onReady || onReady;
  try { const l = await fetch(hdBase + 'list.json?v=' + Math.floor(Date.now() / 36e5)).then(r => r.ok ? r.json() : []); for (const k of l) if (!AVAIL[k]) AVAIL[k] = 1; } catch (e) {}
  // class bodies first so the opening screen already shows them
  await Promise.all((o.preload || []).map(k => hdLoad(k)));
}
function hdLoad(k) {
  if (HD[k] || !AVAIL[k]) return Promise.resolve(HD[k] || null);
  if (PENDING[k]) return PENDING[k];
  return PENDING[k] = fetch(hdBase + k + '.txt?v=3').then(r => { if (!r.ok) throw new Error(r.status); return r.text(); }).then(parseB64).then(g => {
    const hd = HD[k] = autoRig(g.scene, kayKnight, charH * AVAIL[k]);
    hd.mesh.castShadow = true; addRim(hd.mesh.material);
    onReady(k); return hd;
  }).catch(e => { console.warn('HD ' + k, e); AVAIL[k] = 0; return null; });
}
// returns the rigged body if ready; otherwise starts loading it (onReady fires later) and returns null
function hd(k) { if (!k) return null; if (HD[k]) return HD[k]; if (AVAIL[k]) hdLoad(k); return null; }
// weapons on realistic bodies: KayKit hand slots are scaled differently, bows face the other way, spellbooks lie open
function fitProp(w, h) {
  if (!w || !h) return w;
  w.scale.multiplyScalar(CHAR_SCALE * h.slotScale);
  if (/bow/i.test(w.name || '')) w.rotateY(Math.PI);
  if (/spellbook/i.test(w.name || '')) w.rotation.set(0, Math.PI / 2, 0);
  return w;
}

function init(c) {
  renderer = c.renderer; scene = c.scene; camera = c.camera; host = c.host; GLOW_TEX = c.glowTex; MOBILE = !!c.mobile;
  if (c.low) lowFn = c.low; if (c.exposure) expMul = c.exposure; if (c.post) postFn = c.post;
  RING_TEX = softTex('ring'); BEAM_TEX = softTex('beam');
  VX.init(); setupPost();
  // per-game look: lighter vignette / contrast for small top-down boards
  if (post && c.grade) for (const k in c.grade) post.grade.uniforms[k].value = c.grade[k];
  if (c.bloom && post) Object.assign(post.bloom, c.bloom);
}
function assets(c) { CLIPS = c.clips; PROPS = c.props; CHAR_SCALE = c.charScale; }
return { init, assets, render, resize, addRim, VX, hdSetup, hd, fitProp, get hasPost() { return !!post; } };
})();
